version: '3.8'

networks:
  scrape_network:
    driver: bridge

services:
  scrape_sentiment:
    build:
      context: ./deployment/python/
      dockerfile: Dockerfile
    volumes:
      - ./code/python_project/scrape_sentiments:/app/scrape_sentiments
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: sleep infinity
    container_name: p1_scrape_sentiment
    networks:
      - scrape_network
    depends_on:
      - git-sync
      - firefox

  git-sync:
    image: k8s.gcr.io/git-sync/git-sync:v3.6.6
    volumes:
      - ./run/:/git
    environment:
      - GIT_SYNC_REPO=https://github.com/shubhampateliitm/doing-it.git
      - GIT_SYNC_BRANCH=main
      - GIT_SYNC_ROOT=/git
      - GIT_SYNC_WAIT=30
      - GIT_SYNC_ONE_TIME=false
    networks:
      - scrape_network
    

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./run/postgres_data:/var/lib/postgresql/data
    networks:
      - scrape_network

  airflow-webserver:
    build:
      context: ./deployment/airflow
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./run/doing-it.git/code/airflow/dags:/opt/airflow/dags
    depends_on:
      - postgres
    networks:
      - scrape_network
    command: airflow webserver

  airflow-scheduler:
    build:
      context: ./deployment/airflow
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./run/doing-it.git/code/airflow/dags:/opt/airflow/dags
    depends_on:
      - postgres
      - git-sync
    command: airflow scheduler
    networks:
      - scrape_network

  firefox:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
    networks:
      scrape_network:
        aliases:
          - firefox
    shm_size: 2g

volumes:
  postgres_data: