version: '3.8'

networks:
  scrape_network:
    driver: bridge

services:
  scrape_sentiment:
    build:
      context: ./deployment/python/
      dockerfile: Dockerfile
    volumes:
      - ./code/python_project/scrape_sentiments:/app/scrape_sentiments
      - ./code/python_project/deal_with_movies:/app/deal_with_movies
      - ./data:/app/data
    ports:
      - "8000:8000"
      - "22:22"
    environment:
      - PYTHONUNBUFFERED=1
    command: /usr/sbin/sshd -D
    container_name: p1_scrape_sentiment
    networks:
      scrape_network:
        aliases:
          - spark_container
    depends_on:
      - firefox

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./run/postgres_data:/var/lib/postgresql/data
    networks:
      - scrape_network

  airflow-webserver:
    build:
      context: ./deployment/airflow
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./code/airflow/dags:/opt/airflow/dags
      - ./run/airflow:/opt/airflow
      - ./airflow/.ssh:/home/airflow/.ssh:ro
    depends_on:
      - postgres
    networks:
      - scrape_network
    command: airflow webserver

  airflow-scheduler:
    build:
      context: ./deployment/airflow
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./code/airflow/dags:/opt/airflow/dags
      - ./run/airflow:/opt/airflow
      - ./airflow/.ssh:/home/airflow/.ssh:ro
    depends_on:
      - postgres
    command: airflow scheduler
    networks:
      - scrape_network

  firefox:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
    networks:
      scrape_network:
        aliases:
          - firefox
    shm_size: 2g

volumes:
  postgres_data: